### PR TITLE
MVP version of the restaurant page

### PR DESCRIPTION
**Pull request by ozovalihasan**
In this project, I built a restaurant website.

It contains three pages; main page, menu page and contact page. All pages are rendered dynamically. I used webpack for this project.

Please review my project. Thanks in advance.

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @ozovalihasan 
### You have done a good job so far :clap: However, you have a few issues to fix before the project can be approved:-
- [x] Configure `.eslintrc.json `and `.stylelintrc.json` as required and ensure it passes - [follow this guide](https://github.com/microverseinc/linters-config/tree/master/javascript)
- [x] Add more script in the package.json as follows
```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
```
### Make the changes and submit for another code review. Good luck.
- Happy hacking!

**Comment by ozovalihasan** [comment]
Thanks, @rOluochKe for your feedback. I added linter files and updated scripts.

**Review by rOluochKe — APPROVED** [review]
### Well done, you got it right. The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy hacking!

**Comment by ozovalihasan** [comment]
Thanks, @rOluochKe for approval.

**Pull request merged**
